global using Carter;
global using Marten;
global using MediatR;
global using Mapster;
global using FluentValidation;
global using Catalog.API.Models;
global using BuildingBlocks.CQRS;
global using Catalog.API.Exceptions;
global using BuildingBlocks.Behaviors;